### ISSUE TITLE
Modify the layout so that a link to the md file is provided. 

### ISSUE THREAD

**Issue by dvidsilva** [proyectocasablanca/casablanca#10]
include link in translation

**Comment by fvntr** [comment]
I think it should be something like:

La siguiente pagina es una traduccion de: [website link]

and maybe we can hyperlink the title?

**Comment by dvidsilva** [comment]
I opened another issue, there's a separate one, I just figured that maybe we can provide a link to the source markdown file. tho maybe is usless.
