### ISSUE TITLE
Add Open Graph/Twitter meta tags for better sharing

### ISSUE THREAD

**Issue by LaurenMz** [proyectocasablanca/casablanca#26]
It would help with engagement on our Twitter and FB accounts and promote more sharing.

https://developers.facebook.com/docs/sharing/webmasters
https://dev.twitter.com/cards/overview

**Comment by fvntr** [comment]
@LaurenMz do you want to pick this up?

**Comment by LaurenMz** [comment]
@fvntr sure thing
