### ISSUE TITLE
Spanish Language Resources

### ISSUE THREAD

**Issue by LaurenMz** [proyectocasablanca/casablanca#27]
It would be great to have a page for resources, like how to contact senators/officials, register to vote, etc.

**Comment by fvntr** [comment]
@LaurenMz lets start making a list of these, we can keep it under resources in trello

**Comment by dvidsilva** [comment]
The ACLU is a great resource, let's also add a link to their donation page, 

> For those donating, note there are two parts: [the ACLU donations](https://action.aclu.org/what-difference?redirect=node%2F4577) are not tax deductible and funds programs and lobbying efforts. [The ACLU foundation](https://action.aclu.org/secure/sem-support-aclu-foundation?s_src=FNNC170001SEM&ms=gad_SEM_Bing_CFC-Search_ACLU%20Foundation-Branded_aclu%20foundation_p_6124840151) donations are tax deductible and goes to funding litigations.

**Comment by fvntr** [comment]
closing this for now to break down to specific resource lists
