### ISSUE TITLE
Translating issues/standing-up-or-our-law-enforcement-community

### ISSUE THREAD

**Issue by tescobedo** [proyectocasablanca/casablanca#9]
Translate https://www.whitehouse.gov/law-enforcement-community

**Comment by tescobedo** [comment]
https://www.whitehouse.gov/making-our-military-strong-again

**Comment by tescobedo** [comment]
https://www.whitehouse.gov/law-enforcement-community

**Comment by tescobedo** [comment]
Uno de los derechos fundamentales de cada Americano es vivir en una comunidad segura. La administración de Trump va a apoderar a nuestros agentes del orden público para que puedan hacer su trabajo y mantengan nuestras calles libres de crimen y violencia. La administración de Trump va ser una administración de ley y orden público. Le presidente Trump va honrar a nuestros agentes del orden público y los apoyare en su misión de proteger al público. El sentimiento anti-policía en EEUU es peligroso. La administración de Trump le pondrá un fin a este sentimiento. 

La administración de Trump está comprometido a reducir el número de crímenes violentos. En el 2015, homínidas subieron por 17% en cincuenta de las cuidase más grandes de EEUU. Ese es el aumento más grande en 25 años. En la capital, matanzas subieron por 50 por ciento en los últimos cuatro años. Hubieron miles de tiroteos en solo un año en Chicago. 

Nuestra nación necesita más aplicación de la ley, más participación de la comunidad, y una policía más efectiva. 

Nuestro trabajo no es hacer la vida más fácil para el alborotador, el saqueador, o el destructor violento. Nuestro trabajo es hacerle la vida más cómoda a los padres que quieren que sus hijos puedan caminar por la calle sin peligro. O que el anciano esperando el autobús. O el niño pequeño caminando de la escuela a casa. 

Apoyar la aplicación de la ley significa apoyar la habilidad de nuestros ciudadanos de protegerse por sí mismos. Vamos a defender la Segunda Enmienda en cada nivel de nuestro sistema judicial. 

El presidente Trump está comprometido a construir un muro para detener la inmigración ilegal, para detener las pandillas y la violencia, y para detener las drogas derramándose por nuestras comunidades. El está dedicado a hacer cumplir nuestras leyes fronterizas, poner fin a las ciudades santuarios y frenar marea de la ilegalidad asociada con la inmigración ilegal. 

Apoyar la aplicación de la ley también significa deportar a migrantes ilegales con antecedentes criminales violentos que han permanecido dentro de nuestras fronteras. 

Es el primer deber del gobierno de mantener a los inocentes a salvo, y el presidente Trump va a pelear por la seguridad de cada Americano, y en especial por los Americanos que no han conocido un barrio seguro en mucho tiempo.

**Comment by tescobedo** [comment]
@fvntr @dvidsilva How's the translation?

**Comment by dvidsilva** [comment]
http://proyectocasablanca.com/issues/law-enforcement-community/ preview here

**Comment by fvntr** [comment]
Closing since it is up on the site
